// Generated by scripts/generate-capability-manifest.mjs. Do not hand-register packs here.
import type { ApplicationCapabilityPack } from '@awm/capability-sdk';

export const generatedCapabilityPacks: readonly ApplicationCapabilityPack[] = [];
