import { canonicalWorkflowSchema, type CanonicalWorkflow } from './domain.js';
import { migrateWorkflow } from './workflow-migration.js';

export const leadQualificationScope = 'When a new Facebook Lead Ads submission is received, check whether the email address is valid. Enrich the lead using Apollo. If the company has more than 10 employees, create or update the contact in HubSpot and notify the sales team in Slack. Otherwise, add the lead to a Google Sheet for future nurturing. Log all successful and failed executions. If Apollo fails, continue without enrichment and notify the operations team.';

const ids = {
  trigger: '10000000-0000-4000-8000-000000000001', validate: '10000000-0000-4000-8000-000000000002', apollo: '10000000-0000-4000-8000-000000000003', condition: '10000000-0000-4000-8000-000000000004', hubspot: '10000000-0000-4000-8000-000000000005', salesSlack: '10000000-0000-4000-8000-000000000006', sheets: '10000000-0000-4000-8000-000000000007', logger: '10000000-0000-4000-8000-000000000008', operationsSlack: '10000000-0000-4000-8000-000000000009'
} as const;
const node = (id: string, category: CanonicalWorkflow['nodes'][number]['category'], name: string, service: string, operation: string, riskLevel: 'low' | 'medium' | 'high' = 'low'): CanonicalWorkflow['nodes'][number] => ({ id, category, name, description: '', service, operation, purpose: '', expectedResult: '', icon: 'generic-action', estimatedExecution: 'Under 1 minute', inputs: [], outputs: [], credentials: service ? [`${service} connection`] : [], configuration: {}, status: 'incomplete', configurationCompleteness: 50, conditions: [], decisionRule: null, notes: '', bestPractices: [], potentialErrors: [], alternativeImplementations: [], performanceNotes: [], securityNotes: [], riskLevel });
let connectionCounter = 0;
const connection = (sourceNodeId: string, targetNodeId: string, label = '', routeType: CanonicalWorkflow['connections'][number]['routeType'] = 'success'): CanonicalWorkflow['connections'][number] => ({ id: `20000000-0000-4000-8000-${String(++connectionCounter).padStart(12, '0')}`, sourceNodeId, targetNodeId, sourcePort: 'output', targetPort: 'input', label, branchLabel: null, style: routeType === 'error' ? 'failure' : routeType === 'conditional' ? 'conditional' : 'success', condition: null, routeType, mappings: [] });

const now = '2026-01-01T00:00:00.000Z';
export const leadQualificationWorkflow = migrateWorkflow(canonicalWorkflowSchema.parse({
  schemaVersion: '1.0', id: '00000000-0000-4000-8000-000000000100', name: 'Lead Qualification and CRM Update',
  summary: 'Validates and enriches Facebook leads, routes qualified companies to HubSpot, and preserves other leads for nurturing.', objective: 'Automate lead intake and qualification.', targetPlatform: 'n8n', confidence: 0.91, complexity: 'advanced',
  actors: [{ name: 'Sales Team', type: 'human' }, { name: 'Operations Team', type: 'human' }],
  systems: [{ name: 'Facebook Lead Ads', category: 'lead_source' }, { name: 'Apollo', category: 'enrichment' }, { name: 'HubSpot', category: 'crm' }, { name: 'Slack', category: 'notification' }, { name: 'Google Sheets', category: 'storage' }],
  nodes: [node(ids.trigger, 'trigger', 'Receive new lead', 'Facebook Lead Ads', 'New lead'), node(ids.validate, 'action', 'Validate email', 'Email validation service', 'Validate', 'medium'), node(ids.apollo, 'api_request', 'Enrich lead', 'Apollo', 'Enrich person', 'high'), node(ids.condition, 'condition', 'Company has more than 10 employees?', '', 'Compare employee count'), node(ids.hubspot, 'action', 'Create or update contact', 'HubSpot', 'Upsert contact', 'high'), node(ids.salesSlack, 'notification', 'Notify sales team', 'Slack', 'Send channel message'), node(ids.sheets, 'database', 'Add to nurture sheet', 'Google Sheets', 'Create row'), node(ids.logger, 'logger', 'Log execution result', 'Execution log', 'Write record'), node(ids.operationsSlack, 'notification', 'Notify operations of enrichment failure', 'Slack', 'Send channel message')],
  connections: [connection(ids.trigger, ids.validate), connection(ids.validate, ids.apollo), connection(ids.apollo, ids.condition), connection(ids.condition, ids.hubspot, 'More than 10 employees', 'conditional'), connection(ids.hubspot, ids.salesSlack), connection(ids.salesSlack, ids.logger), connection(ids.condition, ids.sheets, '10 employees or fewer', 'conditional'), connection(ids.sheets, ids.logger), connection(ids.apollo, ids.operationsSlack, 'Apollo failed', 'error'), connection(ids.operationsSlack, ids.condition, 'Continue without enrichment')],
  branches: [{ id: '30000000-0000-4000-8000-000000000001', sourceNodeId: ids.condition, name: 'Qualified company', condition: { combinator: 'and', rules: [{ field: 'company.employeeCount', operator: 'greater_than', value: 10 }] }, destinationNodeId: ids.hubspot, isDefault: false }, { id: '30000000-0000-4000-8000-000000000002', sourceNodeId: ids.condition, name: 'Nurture company', condition: null, destinationNodeId: ids.sheets, isDefault: true }],
  errorHandling: [{ id: '40000000-0000-4000-8000-000000000001', nodeId: ids.apollo, strategy: 'fallback', retryAttempts: 1, fallbackNodeId: ids.condition, notificationNodeId: ids.operationsSlack, notes: 'Continue with the original lead data.' }],
  clarificationQuestions: [{ id: '50000000-0000-4000-8000-000000000001', question: 'Which Slack channels should receive sales and operations notifications?', category: 'system', required: true, answer: null, relatedNodeId: ids.salesSlack }],
  risks: [{ id: '60000000-0000-4000-8000-000000000001', category: 'pii', severity: 'high', description: 'Lead contact data contains personally identifiable information.', mitigation: 'Restrict access and avoid including unnecessary fields in logs.', nodeId: ids.trigger }],
  assumptions: ['Employee count is returned by Apollo when enrichment succeeds.'], missingInformation: ['Slack channel identifiers', 'Email validation provider'], warnings: [], recommendations: ['Use idempotent HubSpot upsert keys.', 'Redact personal data from execution logs.'], createdAt: now, updatedAt: now
}));
