import { applicationRegistry, type DataCardinality, type Platform } from '@awm/shared';
import { KNOWLEDGE_CATALOG_VERSION, field, type ApplicationPack, type CanonicalFunctionId, type KnowledgeFieldDefinition, type OperationDefinition, type OperationPlatformMapping } from './types.js';

type MappingSeed = { support?: OperationPlatformMapping['support']; limitation?: string; alternative?: string; implementation?: string };
const mappings = (canonicalFunctionId: CanonicalFunctionId, application: string, operation: string, overrides: Partial<Record<Platform, MappingSeed>> = {}): OperationPlatformMapping[] => (['n8n', 'make', 'zapier'] as const).map((platform) => {
  const override = overrides[platform];
  return { platform, capabilityId: `${platform}.${canonicalFunctionId}`, implementation: override?.implementation ?? `${application} connector — ${operation}`, support: override?.support ?? 'native', limitation: override?.limitation ?? null, alternative: override?.alternative ?? null };
});
const op = (applicationId: string, operationId: string, canonicalFunctionId: CanonicalFunctionId, title: string, purpose: string, requiredInputs: KnowledgeFieldDefinition[], outputs: KnowledgeFieldDefinition[], acceptedInputCardinality: DataCardinality[], producedOutputCardinality: DataCardinality, batchSupported: boolean, previous: CanonicalFunctionId[], next: CanonicalFunctionId[], mistakes: string[], knownPlatformMappings: OperationPlatformMapping[], limitations: string[] = [], alternatives: string[] = []): OperationDefinition => ({ applicationId, operationId, canonicalFunctionId, title, purpose, requiredInputs, outputs, acceptedInputCardinality, producedOutputCardinality, batchSupported, commonPreviousFunctions: previous, commonNextFunctions: next, commonMistakes: mistakes, knownPlatformMappings, limitations, alternatives, catalogVersion: KNOWLEDGE_CATALOG_VERSION });
const legacyApplicationIds: Record<string, string[]> = { 'webhook-api': ['webhook', 'rest-api'], 'generic-crm': [] };
const pack = (applicationId: string, name: string, aliases: string[], category: string, operations: OperationDefinition[]): ApplicationPack => {
  const legacy = applicationRegistry.filter((item) => [applicationId, ...(legacyApplicationIds[applicationId] ?? [])].includes(item.id));
  return { applicationId, name, aliases: [...new Set([...aliases, ...legacy.flatMap((item) => [item.name, ...item.aliases])].map((item) => item.toLowerCase()))], category, operations, catalogVersion: KNOWLEDGE_CATALOG_VERSION };
};

const taskId = field('taskId', 'Task ID', 'string', true, 'Stable Asana task identifier.');
const recordId = field('recordId', 'Record ID', 'string', true, 'Stable destination record identifier.');
const query = field('query', 'Search criteria', 'object', true, 'Structured criteria used to find an existing item.');
const found = field('found', 'Found item', 'object', true, 'Matching item when one exists.');

const asanaId = 'asana';
const asanaOperations: OperationDefinition[] = [
  op(asanaId, 'task-moved-to-section', 'trigger', 'Task Moved to Section', 'Starts when an Asana task enters a configured section or status stage.', [field('projectId', 'Project ID', 'string', true, 'Asana project to monitor.'), field('sectionId', 'Section ID', 'string', true, 'Section that starts the workflow.')], [taskId, field('sectionName', 'Section name', 'string', true, 'Current section name.')], ['single'], 'single', false, [], ['data-retrieval', 'filter'], ['Assuming every connector emits section changes instantly', 'Not filtering unrelated task updates'], mappings('trigger', 'Asana', 'Task updated then filter section', {
    n8n: { support: 'workaround', limitation: 'The Asana Trigger may emit general task updates; filter by the resulting section.', alternative: 'Use an Asana webhook through a generic Webhook trigger.' },
    make: { support: 'workaround', limitation: 'Watch task events and apply a section filter.', alternative: 'Use a custom Asana webhook.' },
    zapier: { support: 'workaround', limitation: 'Available Asana triggers vary; an updated-task trigger may require a Filter step.', alternative: 'Use Webhooks by Zapier if the required section event is unavailable.' },
  }), ['Exact trigger availability depends on connector version and Asana webhook permissions.'], ['Poll task updates and filter by section', 'Receive an Asana webhook']),
  op(asanaId, 'get-task-details', 'data-retrieval', 'Retrieve Task Details', 'Loads the complete Asana task required by downstream steps.', [taskId], [field('task', 'Task details', 'object', true, 'Task fields, custom fields, assignee, and project context.')], ['single'], 'single', false, ['trigger', 'action'], ['validation', 'binary-condition', 'action'], ['Assuming the trigger contains every custom field'], mappings('data-retrieval', 'Asana', 'Get Task')),
  op(asanaId, 'find-subtask', 'data-retrieval', 'Find Subtask', 'Searches for an existing subtask before creating or updating it.', [taskId, field('subtaskName', 'Subtask name', 'string', true, 'Name or unique key of the expected subtask.')], [field('subtask', 'Matching subtask', 'object', false, 'Existing subtask when found.'), field('found', 'Found', 'boolean', true, 'Whether a matching subtask exists.')], ['single'], 'single', false, ['data-retrieval', 'data-transformation'], ['binary-condition'], ['Creating a duplicate subtask without searching first'], mappings('data-retrieval', 'Asana', 'Search subtasks', { zapier: { support: 'workaround', limitation: 'Zapier may require Find Task or Webhooks/API to search subtasks reliably.', alternative: 'Use Webhooks by Zapier with the Asana API.' } })),
  op(asanaId, 'create-subtask', 'action', 'Create Subtask', 'Creates one child task under an existing Asana task.', [field('parentTaskId', 'Parent task ID', 'string', true, 'Parent task receiving the subtask.'), field('name', 'Subtask name', 'string', true, 'Subtask title.')], [field('subtaskId', 'Subtask ID', 'string', true, 'Created subtask identifier.')], ['single'], 'single', false, ['binary-condition', 'validation'], ['action', 'logging', 'merge'], ['Omitting the parent task ID', 'Creating duplicates during retries'], mappings('action', 'Asana', 'Create Task with parent task')),
  op(asanaId, 'update-subtask', 'action', 'Update Subtask', 'Updates an existing Asana subtask instead of creating a duplicate.', [field('subtaskId', 'Subtask ID', 'string', true, 'Existing subtask identifier.'), field('changes', 'Changes', 'object', true, 'Fields to update.')], [field('updatedSubtask', 'Updated subtask', 'object', true, 'Updated task result.')], ['single'], 'single', false, ['binary-condition', 'data-retrieval'], ['merge', 'logging'], ['Updating the parent task instead of the subtask'], mappings('action', 'Asana', 'Update Task')),
  op(asanaId, 'update-task', 'action', 'Update Task', 'Updates fields, description, status, or custom fields on one Asana task.', [taskId, field('changes', 'Changes', 'object', true, 'Fields to update.')], [field('updatedTask', 'Updated task', 'object', true, 'Updated task result.')], ['single'], 'single', false, ['data-retrieval', 'validation'], ['logging', 'end'], ['Overwriting unrelated description content', 'Using an unstable task name instead of task ID'], mappings('action', 'Asana', 'Update Task')),
];

const driveId = 'google-drive';
const driveOperations: OperationDefinition[] = [
  op(driveId, 'find-folder', 'data-retrieval', 'Find Folder', 'Searches for an existing Google Drive folder to prevent duplicates.', [field('folderName', 'Folder name', 'string', true, 'Exact or normalized folder name.'), field('parentFolderId', 'Parent folder ID', 'string', false, 'Optional parent folder scope.')], [field('folder', 'Folder', 'object', false, 'Matching folder when found.'), field('found', 'Found', 'boolean', true, 'Whether the folder exists.')], ['single'], 'single', false, ['data-transformation', 'trigger'], ['binary-condition'], ['Searching globally when the folder must be under a specific parent'], mappings('data-retrieval', 'Google Drive', 'Find Folder', { zapier: { support: 'workaround', limitation: 'Zapier connector search options may require Find File/Folder or API fallback.', alternative: 'Use Webhooks by Zapier with the Drive API.' } })),
  op(driveId, 'create-folder', 'action', 'Create Folder', 'Creates one Google Drive folder after duplicate checks and validation.', [field('folderName', 'Folder name', 'string', true, 'Safe folder name.'), field('parentFolderId', 'Parent folder ID', 'string', false, 'Destination parent folder.')], [field('folderId', 'Folder ID', 'string', true, 'Created folder identifier.'), field('folderUrl', 'Folder URL', 'string', true, 'Shareable folder link subject to permissions.')], ['single'], 'single', false, ['validation', 'binary-condition'], ['action', 'logging', 'merge'], ['Creating duplicate folders during retry', 'Using unsafe characters in folder names'], mappings('action', 'Google Drive', 'Create Folder')),
  op(driveId, 'upload-file', 'action', 'Upload File', 'Uploads one file to a selected Drive folder.', [field('file', 'File', 'object', true, 'File content and metadata.'), field('folderId', 'Folder ID', 'string', true, 'Destination folder.')], [field('fileId', 'File ID', 'string', true, 'Uploaded file identifier.'), field('fileUrl', 'File URL', 'string', true, 'Uploaded file link.')], ['single'], 'single', false, ['iterator', 'validation'], ['logging', 'aggregator'], ['Passing an attachment collection directly without iteration', 'Uploading the same file again on retry'], mappings('action', 'Google Drive', 'Upload File')),
];

const sheetsId = 'google-sheets';
const sheetsOperations: OperationDefinition[] = [
  op(sheetsId, 'list-rows', 'data-retrieval', 'Retrieve Rows', 'Retrieves a filtered collection of Google Sheets rows for iterator-based processing.', [field('spreadsheetId', 'Spreadsheet ID', 'string', true, 'Source spreadsheet.'), field('filter', 'Row filter', 'object', false, 'Optional verified row selection criteria.')], [field('rows', 'Rows', 'array', true, 'Matching spreadsheet rows.')], ['single'], 'collection', false, ['trigger'], ['iterator', 'aggregator'], ['Retrieving an unbounded sheet without a filter or range'], mappings('data-retrieval', 'Google Sheets', 'Get Many Rows', {
    zapier: { support: 'workaround', limitation: 'Zapier may require Find Many Spreadsheet Rows or a Looping step depending on the connector version.', alternative: 'Use a verified Find Many Rows action, or the Google Sheets API through Webhooks.' },
  })),
  op(sheetsId, 'add-row', 'action', 'Add Row', 'Adds exactly one record as one Google Sheets row.', [field('spreadsheetId', 'Spreadsheet ID', 'string', true, 'Target spreadsheet.'), field('sheetName', 'Sheet name', 'string', true, 'Target worksheet.'), field('rowData', 'Row data', 'object', true, 'One record mapped to columns.')], [field('rowNumber', 'Row number', 'number', true, 'Appended row index.')], ['single'], 'single', false, ['iterator', 'validation', 'data-transformation'], ['logging', 'loop', 'end'], ['Passing an entire collection to Add Row', 'Missing required column mappings', 'Duplicating rows during retry'], mappings('action', 'Google Sheets', 'Add Row')),
  op(sheetsId, 'append-rows-batch', 'action', 'Append Multiple Rows via Sheets API', 'Appends a collection of rows through a batch-capable Google Sheets API request.', [field('spreadsheetId', 'Spreadsheet ID', 'string', true, 'Target spreadsheet.'), field('range', 'Range', 'string', true, 'Target sheet range.'), field('rows', 'Rows', 'array', true, 'Collection of row arrays.')], [field('updatedRange', 'Updated range', 'string', true, 'Range written by the API.')], ['collection'], 'collection', true, ['validation', 'data-transformation'], ['logging', 'end'], ['Assuming every native connector exposes the batch API', 'Mixing rows with different column shapes'], mappings('action', 'Google Sheets API', 'Append values batch', {
    n8n: { support: 'workaround', limitation: 'Use HTTP Request for the explicit Sheets values API batch or let the native node process multiple input items.', alternative: 'Iterator plus Add Row.' },
    make: { support: 'workaround', limitation: 'The native Add a Row module processes bundles; use HTTP for one explicit batch request.', alternative: 'Iterator plus Add a Row.' },
    zapier: { support: 'unsupported', limitation: 'The native Google Sheets action does not expose a general multi-row batch append operation.', alternative: 'Use Looping by Zapier with Add Row or Webhooks/API.' },
  }), ['Native connector batch equivalence differs by platform.'], ['Iterator plus Add Row']),
  op(sheetsId, 'lookup-row', 'data-retrieval', 'Lookup Row', 'Finds an existing spreadsheet row using a unique key.', [field('spreadsheetId', 'Spreadsheet ID', 'string', true, 'Target spreadsheet.'), query], [field('row', 'Matching row', 'object', false, 'Matching row when found.'), field('found', 'Found', 'boolean', true, 'Whether a row matched.')], ['single'], 'single', false, ['trigger', 'data-transformation'], ['binary-condition'], ['Using a non-unique lookup key'], mappings('data-retrieval', 'Google Sheets', 'Lookup Row')),
];

const gmailId = 'gmail';
const gmailOperations: OperationDefinition[] = [
  op(gmailId, 'new-email', 'trigger', 'New Email', 'Starts a workflow when a matching Gmail message arrives.', [field('mailbox', 'Mailbox', 'string', false, 'Mailbox or label to monitor.')], [field('message', 'Email message', 'object', true, 'Message metadata and content.')], ['single'], 'single', false, [], ['validation', 'data-retrieval', 'filter'], ['Processing automated replies or spam without filtering'], mappings('trigger', 'Gmail', 'New Email')),
  op(gmailId, 'send-email', 'action', 'Send Email', 'Sends one email using a configured Gmail connection.', [field('recipient', 'Recipient', 'string', true, 'Validated destination email address.'), field('subject', 'Subject', 'string', true, 'Email subject.'), field('body', 'Message body', 'string', true, 'Approved email content.')], [field('messageId', 'Message ID', 'string', true, 'Sent Gmail message identifier.')], ['single'], 'single', false, ['validation', 'data-transformation', 'binary-condition'], ['logging', 'delay', 'end'], ['Sending without checking opt-out or response state', 'Retrying sends without idempotency'], mappings('action', 'Gmail', 'Send Email')),
  op(gmailId, 'search-email', 'data-retrieval', 'Search Email', 'Searches Gmail for a reply or matching conversation.', [field('searchQuery', 'Search query', 'string', true, 'Gmail-compatible search expression.')], [field('messages', 'Messages', 'array', true, 'Matching messages.')], ['single'], 'collection', false, ['delay', 'trigger'], ['binary-condition', 'iterator'], ['Treating an empty collection as a found message'], mappings('data-retrieval', 'Gmail', 'Search Email', { zapier: { support: 'workaround', limitation: 'Gmail search availability varies by Zapier action set.', alternative: 'Use Gmail Find Email or the Gmail API through Webhooks.' } })),
];

const slackId = 'slack';
const slackOperations: OperationDefinition[] = [
  op(slackId, 'new-message', 'trigger', 'New Message', 'Starts when a Slack message matches the configured channel/event.', [field('channelId', 'Channel ID', 'string', true, 'Channel to monitor.')], [field('message', 'Slack message', 'object', true, 'Message payload.')], ['single'], 'single', false, [], ['filter', 'data-retrieval'], ['Triggering on bot messages and creating loops'], mappings('trigger', 'Slack', 'New Message')),
  op(slackId, 'send-channel-message', 'notification', 'Send Channel Message', 'Notifies a Slack channel with workflow information.', [field('channelId', 'Channel ID', 'string', true, 'Destination channel.'), field('message', 'Message', 'string', true, 'Notification text.')], [field('timestamp', 'Message timestamp', 'string', true, 'Created Slack message timestamp.')], ['single'], 'single', false, ['action', 'error-handler', 'manual-review'], ['logging', 'end'], ['Posting personal data to a broad channel'], mappings('notification', 'Slack', 'Send Channel Message')),
  op(slackId, 'send-direct-message', 'notification', 'Send Direct Message', 'Notifies one Slack user directly.', [field('userId', 'User ID', 'string', true, 'Destination Slack user.'), field('message', 'Message', 'string', true, 'Notification text.')], [field('timestamp', 'Message timestamp', 'string', true, 'Created message timestamp.')], ['single'], 'single', false, ['action', 'error-handler'], ['end'], ['Using an email address where a Slack user ID is required'], mappings('notification', 'Slack', 'Send Direct Message')),
];

const apiId = 'webhook-api';
const apiOperations: OperationDefinition[] = [
  op(apiId, 'receive-webhook', 'trigger', 'Receive Webhook', 'Starts a workflow from an authenticated inbound HTTP request.', [field('path', 'Webhook path', 'string', true, 'Unique inbound endpoint path.')], [field('payload', 'Request payload', 'object', true, 'Validated inbound request body.')], ['single'], 'single', false, [], ['validation', 'data-transformation'], ['Accepting unauthenticated or unvalidated requests'], mappings('trigger', 'Webhook', 'Receive Request')),
  op(apiId, 'http-request', 'action', 'Send HTTP Request', 'Calls an external API operation not available through a native connector.', [field('url', 'URL', 'string', true, 'Approved API endpoint.'), field('method', 'HTTP method', 'string', true, 'Request method.'), field('body', 'Request body', 'object', false, 'Validated request body.')], [field('response', 'Response', 'object', true, 'Parsed API response.')], ['single'], 'single', false, ['validation', 'data-transformation'], ['binary-condition', 'logging', 'error-handler'], ['Placing secrets in node descriptions', 'Ignoring rate limits and pagination'], mappings('action', 'HTTP/Webhook', 'Custom Request'), ['Authentication, rate limits, and response schemas are API-specific.'], ['Use a native application connector when it supports the operation.']),
  op(apiId, 'paginated-request', 'data-retrieval', 'Retrieve Paginated Records', 'Retrieves multiple API pages under an explicit stop condition.', [field('url', 'URL', 'string', true, 'Collection endpoint.'), field('pagination', 'Pagination configuration', 'object', true, 'Token/page and stop rules.')], [field('records', 'Records', 'array', true, 'Combined records from all pages.')], ['single'], 'collection', false, ['trigger', 'action'], ['iterator', 'aggregator'], ['Missing the no-next-page stop rule', 'Ignoring maximum page boundaries'], mappings('data-retrieval', 'HTTP/Webhook', 'Paginated Request', {
    zapier: { support: 'workaround', limitation: 'Zapier has no universal native pagination loop for arbitrary APIs.', alternative: 'Use a Code step, multiple Zaps with stored state, or an external service.' },
  })),
];

const crmId = 'generic-crm';
const crmOperations: OperationDefinition[] = [
  op(crmId, 'find-record', 'data-retrieval', 'Find CRM Record', 'Finds one CRM record using a stable unique identifier.', [field('recordType', 'Record type', 'string', true, 'Contact, company, lead, or opportunity.'), query], [found, field('found', 'Found', 'boolean', true, 'Whether a matching record exists.')], ['single'], 'single', false, ['trigger', 'data-transformation'], ['binary-condition'], ['Searching by a non-unique display name'], mappings('data-retrieval', 'CRM', 'Find Record', { n8n: { support: 'unknown', limitation: 'Exact support depends on the selected CRM connector.', alternative: 'Use HTTP Request with the CRM API.' }, make: { support: 'unknown', limitation: 'Exact support depends on the selected CRM module.', alternative: 'Use HTTP with the CRM API.' }, zapier: { support: 'unknown', limitation: 'Exact support depends on the selected CRM application.', alternative: 'Use Webhooks by Zapier with the CRM API.' } })),
  op(crmId, 'create-record', 'action', 'Create CRM Record', 'Creates one CRM record after validation and duplicate checks.', [field('recordType', 'Record type', 'string', true, 'CRM object type.'), field('recordData', 'Record data', 'object', true, 'Mapped record fields.')], [recordId], ['single'], 'single', false, ['binary-condition', 'validation'], ['logging', 'merge'], ['Creating duplicates without a prior search'], mappings('action', 'CRM', 'Create Record', { n8n: { support: 'unknown', limitation: 'Exact fields and operation support depend on the selected CRM connector.', alternative: 'Use HTTP Request.' }, make: { support: 'unknown', limitation: 'Exact fields and operation support depend on the selected CRM module.', alternative: 'Use HTTP.' }, zapier: { support: 'unknown', limitation: 'Exact fields and operation support depend on the selected CRM application.', alternative: 'Use Webhooks by Zapier.' } })),
  op(crmId, 'update-record', 'action', 'Update CRM Record', 'Updates one existing CRM record.', [recordId, field('changes', 'Changes', 'object', true, 'Fields to update.')], [recordId], ['single'], 'single', false, ['data-retrieval', 'binary-condition'], ['logging', 'merge'], ['Updating the wrong record after an ambiguous search'], mappings('action', 'CRM', 'Update Record', { n8n: { support: 'unknown', limitation: 'Exact support depends on the selected CRM connector.' }, make: { support: 'unknown', limitation: 'Exact support depends on the selected CRM module.' }, zapier: { support: 'unknown', limitation: 'Exact support depends on the selected CRM application.' } })),
  op(crmId, 'upsert-record', 'action', 'Create or Update CRM Record', 'Creates or updates one record using a supported unique key.', [field('uniqueKey', 'Unique key', 'object', true, 'Field and value used for upsert.'), field('recordData', 'Record data', 'object', true, 'Fields to create or update.')], [recordId], ['single'], 'single', false, ['validation', 'data-transformation'], ['logging', 'end'], ['Assuming every CRM exposes a native upsert operation'], mappings('action', 'CRM', 'Upsert Record', { n8n: { support: 'unknown', limitation: 'Some CRM connectors require an explicit Find then Create/Update pattern.', alternative: 'Use Find Record followed by Binary Condition.' }, make: { support: 'unknown', limitation: 'Some CRM modules require Search then Create/Update.', alternative: 'Use Search followed by Router.' }, zapier: { support: 'unknown', limitation: 'Some CRM apps offer Create or Update; others require Find then Paths.', alternative: 'Use Find followed by Paths.' } })),
];

export const applicationPacks: readonly ApplicationPack[] = [
  pack(asanaId, 'Asana', ['asana'], 'project-management', asanaOperations),
  pack(driveId, 'Google Drive', ['drive', 'gdrive'], 'storage', driveOperations),
  pack(sheetsId, 'Google Sheets', ['sheets', 'spreadsheet'], 'spreadsheet', sheetsOperations),
  pack(gmailId, 'Gmail', ['google mail'], 'email', gmailOperations),
  pack(slackId, 'Slack', ['slack messaging'], 'messaging', slackOperations),
  pack(apiId, 'Webhook / Generic API', ['webhook', 'generic api', 'rest api', 'http'], 'api', apiOperations),
  pack(crmId, 'Generic CRM', ['crm', 'customer relationship management'], 'crm', crmOperations),
];

export function getApplicationPack(applicationIdOrAlias: string): ApplicationPack | undefined {
  const key = applicationIdOrAlias.trim().toLowerCase();
  return applicationPacks.find((item) => item.applicationId === key || item.name.toLowerCase() === key || item.aliases.some((alias) => alias.toLowerCase() === key));
}
export function getOperation(applicationIdOrAlias: string, operationId: string): OperationDefinition | undefined { return getApplicationPack(applicationIdOrAlias)?.operations.find((item) => item.operationId === operationId); }
