import { KNOWLEDGE_CATALOG_VERSION, canonicalFunctionIds, field, type CanonicalFunctionDefinition, type CanonicalFunctionId, type CompatibilityRule, type KnowledgeFieldDefinition } from './types.js';

const input = field('input', 'Input data', 'unknown', true, 'Data received from the previous workflow step.');
const result = field('result', 'Step result', 'unknown', true, 'Result made available to downstream workflow steps.');
const rule = (id: string, kind: CompatibilityRule['kind'], value: string, message: string): CompatibilityRule => ({ id, kind, value, message });
const definition = (id: CanonicalFunctionId, purpose: string, useWhen: string[], doNotUseWhen: string[], acceptedCardinality: CanonicalFunctionDefinition['acceptedCardinality'], compatibilityRules: CompatibilityRule[], previous: CanonicalFunctionId[], next: CanonicalFunctionId[], mistakes: string[], requiredInputs: KnowledgeFieldDefinition[] = [input], outputs: KnowledgeFieldDefinition[] = [result]): CanonicalFunctionDefinition => ({ id, canonicalType: id, purpose, useWhen, doNotUseWhen, requiredInputs, outputs, acceptedCardinality, compatibilityRules, commonPreviousFunctions: previous, commonNextFunctions: next, commonMistakes: mistakes, platformCapabilityReferences: [`n8n.${id}`, `make.${id}`, `zapier.${id}`], catalogVersion: KNOWLEDGE_CATALOG_VERSION });

export const canonicalFunctionRegistry: readonly CanonicalFunctionDefinition[] = [
  definition('trigger', 'Start a workflow when a defined event occurs.', ['An application event, webhook, schedule, or message starts the process.'], ['The step only reads, transforms, or evaluates existing data.'], ['single', 'collection', 'unknown'], [rule('trigger.no-incoming', 'semantic', 'no-primary-input', 'A trigger starts a workflow and should not depend on a normal incoming execution edge.')], [], ['data-retrieval', 'validation', 'action'], ['Using a trigger for data retrieval', 'Omitting the source application or event'], [], [field('event', 'Event payload', 'object', true, 'Payload emitted by the triggering system.')]),
  definition('action', 'Perform one specific operation in an application.', ['A record, message, file, or task must be created, updated, sent, or deleted.'], ['The step is only reading data or selecting a route.'], ['single', 'collection', 'unknown'], [], ['validation', 'data-transformation', 'binary-condition', 'iterator'], ['action', 'notification', 'logging', 'end'], ['Combining unrelated operations', 'Using a generic Action Node title']),
  definition('data-retrieval', 'Load information required by later steps.', ['The trigger lacks required fields or an existing record must be searched.'], ['The operation mutates external data.'], ['single', 'collection', 'unknown'], [], ['trigger', 'action', 'iterator'], ['validation', 'filter', 'binary-condition', 'action'], ['Skipping retrieval when required identifiers are absent'], [field('lookup', 'Lookup criteria', 'object', true, 'Identifiers or filters used to retrieve data.')], [field('records', 'Retrieved data', 'unknown', true, 'One record or a collection returned by the source.')]),
  definition('data-transformation', 'Normalize, format, parse, or derive data without external side effects.', ['A target operation needs a different format or derived value.'], ['The workflow needs a business decision or external update.'], ['single', 'collection', 'unknown'], [], ['data-retrieval', 'trigger', 'iterator'], ['validation', 'action', 'aggregator'], ['Hiding business decisions inside transformation code']),
  definition('validation', 'Verify that data is usable before continuing.', ['Required fields, formats, ranges, or safety rules must be checked.'], ['The question chooses a business outcome rather than data validity.'], ['single', 'collection', 'unknown'], [rule('validation.rule', 'semantic', 'validation-rule', 'Validation requires an explicit data-quality rule.')], ['trigger', 'data-retrieval', 'data-transformation'], ['filter', 'binary-condition', 'action', 'manual-review'], ['Confusing data validation with a business condition']),
  definition('filter', 'Continue matching records and silently stop unmatched records.', ['Only matching records continue and unmatched records require no action.'], ['The false outcome needs notification, review, or another business action.'], ['single', 'collection'], [rule('filter.stop', 'unmatched_behavior', 'stop', 'Unmatched records must stop without a business action.')], ['validation', 'data-retrieval', 'trigger'], ['action', 'iterator', 'end'], ['Using a filter when the false path has work']),
  definition('binary-condition', 'Route execution into exactly two meaningful outcomes.', ['A true/false, found/not-found, approved/rejected, or equivalent decision has two active outcomes.'], ['There are three or more outcomes or the unmatched case simply stops.'], ['single'], [rule('binary.two-outcomes', 'requires_outcomes', '2', 'A binary condition requires exactly two meaningful outcomes.')], ['validation', 'data-retrieval', 'delay', 'action'], ['action', 'merge', 'manual-review', 'end'], ['Creating only one branch', 'Using duplicate branch outcomes']),
  definition('multi-route-decision', 'Route execution among multiple meaningful outcomes.', ['A service, region, status, product, or priority has three or more routes.'], ['There are exactly two outcomes.'], ['single'], [rule('router.multiple', 'requires_outcomes', '3+', 'A multi-route decision represents three or more meaningful routes.')], ['data-retrieval', 'validation', 'data-transformation'], ['action', 'merge', 'manual-review'], ['Using a binary IF for several outcomes', 'Omitting a fallback route when values may be unknown']),
  definition('iterator', 'Emit each item from a collection for per-item processing.', ['Every item in an array, batch, attachment list, or result set needs individual work.'], ['The input is one object or the target supports the complete collection as a batch.'], ['collection'], [rule('iterator.collection', 'requires_cardinality', 'collection', 'An iterator requires collection input.'), rule('iterator.no-single', 'forbids_cardinality', 'single', 'Do not iterate a single record.')], ['data-retrieval', 'validation', 'binary-condition'], ['action', 'validation', 'aggregator', 'loop'], ['Iterating a single item', 'Retrying per-item creates without idempotency']),
  definition('loop', 'Repeat a controlled sequence until a condition or boundary is reached.', ['Follow-ups, retries, pagination, or reminders repeat under a stop rule.'], ['A collection only needs one pass per item.'], ['single', 'collection'], [rule('loop.boundary', 'requires_boundary', 'attempt-limit-or-timeout', 'Every loop requires a stop condition, limit, and exit path.')], ['action', 'delay', 'binary-condition'], ['action', 'delay', 'binary-condition', 'end'], ['Creating an infinite cycle', 'Omitting the exit path']),
  definition('merge', 'Rejoin compatible workflow branches before shared downstream work.', ['Two or more branches should continue through the same next sequence.'], ['Item results must be combined into one value or branches should remain terminal.'], ['single', 'collection', 'unknown'], [rule('merge.incoming', 'requires_incoming_branches', '2+', 'A merge requires at least two incoming branches.')], ['binary-condition', 'multi-route-decision', 'action'], ['action', 'notification', 'end'], ['Using merge instead of aggregation', 'Merging branches with incompatible downstream data']),
  definition('aggregator', 'Combine multiple item results into one collection or summary.', ['Iterated results must become one array, report, digest, or object.'], ['The goal is only to reconnect control-flow branches.'], ['collection'], [rule('aggregator.collection', 'requires_cardinality', 'collection', 'An aggregator requires multiple item results.')], ['iterator', 'loop', 'action'], ['action', 'notification', 'end'], ['Using an aggregator for branch convergence', 'Omitting the aggregation method']),
  definition('delay', 'Pause execution for a duration, date, or external resume event.', ['A reminder, follow-up, scheduled action, or response wait must pause.'], ['The step is only a visual spacer.'], ['single', 'collection', 'unknown'], [rule('delay.boundary', 'requires_boundary', 'duration-date-or-event', 'A delay needs a duration, target date, or resume event.')], ['action', 'notification', 'loop'], ['binary-condition', 'action', 'loop'], ['Omitting timezone for date-based waits']),
  definition('human-approval', 'Pause until a person approves, rejects, or times out.', ['Risk, cost, policy, or content requires a human decision.'], ['The decision can be evaluated entirely from data.'], ['single'], [rule('approval.outcomes', 'requires_outcomes', 'approved-rejected-timeout', 'Approval needs approved, rejected, and no-response handling.')], ['action', 'validation', 'notification'], ['binary-condition', 'action', 'manual-review'], ['Omitting the approver or deadline']),
  definition('retry', 'Repeat a recoverable technical operation within safe limits.', ['Temporary timeouts, rate limits, or service outages are retryable.'], ['The failure is a permanent business rejection.'], ['single', 'collection', 'unknown'], [rule('retry.boundary', 'requires_boundary', 'attempt-limit', 'Retry requires maximum attempts and final failure behavior.')], ['action', 'error-handler'], ['action', 'error-handler', 'manual-review'], ['Retrying validation errors', 'Creating duplicate external records']),
  definition('error-handler', 'Capture a technical failure and route it to a safe response.', ['An operation can fail and needs logging, retry, fallback, notification, or review.'], ['The branch represents a normal business decision.'], ['single', 'collection', 'unknown'], [], ['action', 'retry', 'data-retrieval'], ['retry', 'notification', 'manual-review', 'end'], ['Showing every technical failure in the default business flow']),
  definition('notification', 'Inform a person or channel about an event or required action.', ['A user, owner, administrator, or team must be informed.'], ['The message is the primary customer-facing business operation and should be a specific action.'], ['single', 'collection', 'unknown'], [], ['action', 'error-handler', 'manual-review'], ['logging', 'end', 'human-approval'], ['Using an unspecified messaging provider']),
  definition('logging', 'Record execution evidence for audit, troubleshooting, or reporting.', ['Important execution results, decisions, or failures need a trace.'], ['Logging would expose unnecessary secrets or personal data.'], ['single', 'collection', 'unknown'], [], ['action', 'error-handler', 'notification'], ['action', 'end'], ['Logging credentials or excessive personal data']),
  definition('manual-review', 'Place an unresolved item into a human work queue.', ['Automation cannot safely determine the next action or repeated failure needs investigation.'], ['A synchronous approval decision is required before continuing.'], ['single', 'collection', 'unknown'], [], ['validation', 'error-handler', 'human-approval', 'multi-route-decision'], ['notification', 'end'], ['Treating manual review as an automatic approval']),
  definition('end', 'Mark a defined terminal workflow outcome.', ['A success, stop, escalation, rejection, or manual-review route finishes.'], ['More automated work must continue.'], ['single', 'collection', 'unknown'], [rule('end.no-outgoing', 'semantic', 'terminal', 'An End function must not have a normal outgoing route.')], ['action', 'notification', 'manual-review', 'merge'], [], ['Using a vague End title that does not identify the outcome']),
];

export function getCanonicalFunction(id: CanonicalFunctionId): CanonicalFunctionDefinition | undefined { return canonicalFunctionRegistry.find((item) => item.id === id); }
export function isCanonicalFunctionId(value: string): value is CanonicalFunctionId { return (canonicalFunctionIds as readonly string[]).includes(value); }
